language: python
python:
- 2.7
services:
- docker
jobs:
  include:
  - stage: deploy-dev
    if: branch = master AND type = push
    before_script:
    - docker pull philm/ansible_playbook
    - openssl aes-256-cbc -K $encrypted_276c776368d5_key -iv $encrypted_276c776368d5_iv
      -in deployment-key.enc -out ~/.ssh/id_rsa -d
    script:
    - docker run -it -v ~/.ssh/id_rsa:/root/.ssh/id_rsa -v "$(pwd)":/ansible/playbooks
      -e DB_USER=$DB_USER -e DB_PASSWORD=$DB_PASSWORD -e GITHUB_CLIENT_SECRET=$GITHUB_CLIENT_SECRET
      -e GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID philm/ansible_playbook dev-deploy.yml
      --private-key=~/.ssh/id_rsa -u ubuntu -i dev_hosts
  - stage: deploy-production
    if: branch = production AND type = push
    before_script:
    - docker pull philm/ansible_playbook
    - openssl aes-256-cbc -K $encrypted_276c776368d5_key -iv $encrypted_276c776368d5_iv
      -in deployment-key.enc -out ~/.ssh/id_rsa -d
    script:
    - docker run -it -v ~/.ssh/id_rsa:/root/.ssh/id_rsa -v "$(pwd)":/ansible/playbooks
      -e DB_USER=$DB_USER -e DB_PASSWORD=$DB_PASSWORD -e GITHUB_CLIENT_SECRET=$GITHUB_CLIENT_SECRET
      -e GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID philm/ansible_playbook production-deploy.yml
      --private-key=~/.ssh/id_rsa -u ubuntu -i production_hosts
notifications:
  email: true
env:
  global:
  - secure: AQ95UgWsqVljAbXZ8luUTtOF4KHYv4Qp3tHCuXIWVW+Y91lJdej7jkgY495957UUqZCQwVK/e+o+8oOP+LVcxvLrkGPosKTlVHlR2GdAoDU8DE8m0JpJ63b1inNBNaDozgZW93/9lX/ykxMLE80jJBL0UKnEjRuo3zYTafCCKx60Rb+endg/IIBFLbl3T7SMAMmZmwOoOzEvqF39De4sIWHipA35X0zMGMFIMgGGoE9o6/rOQjJZtfNMd79G6eYvwP7+GHMJJCGo7ITQK1/vuL97Zn1ujyj6qmjfGZH33Vb5Fe4VNS7cnRPP+euhxrIee0F10kA9gNwBZZmS4FpfCWkUxUr2XfNgG5LE5vJJrxxPckdHLt8gWFTev7HM+xbBkoR3Yn8o0qeMki+6OiV7Roc6t4i6oVcnS4Ux6y/NfrB0N/l9+0PQKUkQFY8+b9BPtHFbAaVc7cwI3t8+/SBDWxl3RCjPkup9fw0thbEOszcMGlfNl/fs5zbnUyQk9huLkmLPI/NZ++jFvP9iIg6SYv8NPEIDshsD0nFF+uz09zp6hx65bNzjXyi7DDG4D98VpCj2hBZ/7TbfmXio61fJkXSNwrwvvp/x+rUOxUcn5ptMKL/oqTwQhv8sBkO92hFe0cz7mARtH7WLGhbJ8PQed4D8OWKacN1NxM54ZYlaJtU=
  - secure: aP5mOqneJbY/dixxoGdNe7A/5Cvm8n2LG8yKUJ3jVMqRq7zfWV0/ey5TM7sK3UR+JgXzrUS7PzZ64gl+udQcjk/gFE57Y8WlEn+9JrsWGqyJbW8x0Q35Z08ya7jUpzgzn7w1BY9TneBULsImK0KaoaTt7m2ZZPuOkdaTZlmFE0VTGPBRh3/ess1DaZMS1ss2PRb/qlZWzg20FbAxEntmnuapKaKItepAP0bVS68TIU88sSf3b+qgqQqDj5HhrgDUYJuRxnbVoRgj4hWY7pc5zmcqpXf+K+KVqhUf/+Vj5JMTwoqsCL6pVwTu9H0mr9eXFr+346xLGYPeciAqMMyPIF4+TEPmZubg3O2HnkQplwd55fQSYF1LWfpxoHy16RnOQ5VT/lu7f63NtWbBDATzOAAoDVywWwNotHCAmQXDFePZ2syd19diQh+ilFfyN5Ln/BU882IqHSbzA7HMX/7K047pIdMBhDhyxrbcHNkZDtLmrR3xRVI1IEoBVV6CBUhcsk7Oz8n/YVI1lFvAMXT2Xy4VgnbsKrn2kHS7faheQqTM/kkbk+K7PaDpOt5Bh3PUngCBSJbFZdL8txMSenRkei03WvQwK4WSQ3KCqQ5Oe67RMnLj5E2ZDceApwptHQb0HhddZU4cNsLK/UP8kqotmvFkjj8brd/wJFMmwp6z4/s=
  - secure: xg7GT7sVIdAPgtMKhGeN8Wd1z+6r4X7/+JsvBho3kJRkoK2LRVxYjE7LJJ7NLRmX4Ba09RvzMig8WqGw8WD1dllyqcIRuHNEmJZ02b4PbotKnnzQ62ntuwIB37Ti3KkxYOR26QMRf+dIDvtKs69whUW7THL/VX8c2r71kM/jUeRFQmi6vxaG+AanHp6xwVQvIrIqAxpxfYDn8hbPTK+8Ha9iSyv12XwpY7elQOy9S22EQUpYP8rOD38uD8/WCY7ldGNr4zr1UcsDR/WeVINoLR85eAI7aLzzxp1M7gjQT+gj57Q3PaICWOavk7Gdceo79PfsP3xnaAt/ItWvXLgFTjenJ++7wXgx34loZKKiuEbHqHSSVWXNFReeeZHV249IqI9M9i4Cp/2XfsVIIwa0VreW5XamwE+fb3ZgO9wOw+F9Fts8lAmbEEeM/MqsFkIQ1ZuZTh9zL0pJR503Ar/UJUKi0591qVHmJDxLlSunxWfu38gVqgum+6UdRWWIjQ3j5KNlC4oxZO/xwv1mwMq0c1RMiOnth6YCZmkI9yIMIc1TAKQTe+MGgi/xc5WTPyXs90T26/5qtBzUVWOvc7b0Ia9vr8qytoYHT5zDKEQwdoULnCS4nCSkX5MDDV8fg/sXACRAv995zr41/flIHKohfJiDHt60gqJrURxPfOmg4Bs=
  - secure: k8Pzyb7Dwp5t5TOOIw4hrymyvueFg/y7AhU9LZMGG2jNp5zQtryPMMOM0akP0MF1VWScQJ/az8fsiiVOF0M3bb7HySgCkscxbf99Xd/4o9vC7HB0jWosjwEg8JpNIEjSjIS5xNr+VLoYWfIAzvlSji7CT1baqCioc/+PqY3rJITtiwBBq6AcIjklwVNK+Zic/piIq3cBeoREccal3e4EhTMJhgr3x6t3f+SVyIrFGwrdjKR5OtaMZshdX8HINhPkiV38BIvu0B1oVzbAe+8TlSUFJvwa2F0zh2MsIGDvnuoxNxf+2wMWEaMDeKvFEAVNOFO8GJQ+W2jGN51FIHCKpFPklY4XtX8DnrmHIT9HGH7unHi17gVTt4/Zo00pe/xbk7/UkxvMPibAjYlA4QlquMvhprYoG0hOH0uBmlxwTLb2HVUSMWI808v3DpXhQ8CWUvUAGeD4dAId1+GgvY+JINvOqewhtuX92nRf7fsdxmx+Bk32L1V1fY2s3xFRD5vSvNTfeDu0RTBP/SOGbwu1EAzHsrdv5i2oMDuopmLTq97dM+qJEpXoFE85ZyjQpCPL+QgmkWjezYvqpNFRbGBKRV77hVpRpNytHtGRpoXhtPQgxpkbjrtZyLeLk91958yk3F3OARa6dQeF9cvXICSec1p49App7TWxm5mzsX8Q+64=
