# Create the virtualenv and install the dependencies

- name: Create the virtualenv
  command: virtualenv -p {{ virtualenv_python_version }} {{ venv_dir }}
          creates={{ venv_dir }}/bin/activate

- name: Ensure gunicorn and pycurl are installed in the virtualenv
  pip: virtualenv={{ venv_dir }} name={{ item }}
  with_items:
    - gunicorn
    - psycopg2

- name: Install packages required by the Django app inside virtualenv
  pip: virtualenv={{ venv_dir }} requirements={{ requirements_file }}