# Clone frontend code repository, install npm dependencies

- name: Clone or pull the latest code
  git: repo={{ frontend_repository_url }}
        dest={{ frontend_dir }}
  become: yes

- name: Create DB_Config.js file
  template: src=JS_DB_Config dest="{{ frontend_dir }}/src/DB_CONFIG.js"
  when: not (nginx_use_letsencrypt is defined and nginx_use_letsencrypt)

- name: Create DB_Config.js file (SSL)
  template: src=JS_DB_Config_ssl dest="{{ frontend_dir }}/src/DB_CONFIG.js"
  when: nginx_use_letsencrypt is defined and nginx_use_letsencrypt

- name: Run the script
  shell: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  become: yes

- name: Update
  command: apt-get update
  become: yes

- name: Install Node.js from the distributions repository
  apt: name=nodejs state=latest
  become: yes

- name: Install packages based on package.json.
  npm:
    path: "{{ frontend_dir }}"
  become: yes

- name: npm build
  command: npm run build
  args:
    chdir: "{{ frontend_dir }}"
  become: yes