# Clone frontend code repository, install npm dependencies

- name: Clone or pull the latest code
  git: repo={{ frontend_repository_url }}
        dest={{ frontend_dir }}
  become: yes

- name: Run the script
  shell: curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  become: yes

- name: Update
  command: apt-get update
  become: yes

- name: Install Node.js from the distributions repository
  apt: name=nodejs state=latest
  become: yes

- name: Install packages based on package.json.
  npm:
    path: "{{ frontend_dir }}"
  become: yes

- name: npm build
  command: npm run build
  args:
    chdir: "{{ frontend_dir }}"
  become: yes