# Configure nginx web server

- name: Set up nginx config
  apt: name=nginx state=latest
  become: yes

- name: Write nginx conf file
  template: src=nginx.conf dest=/etc/nginx/sites-available/{{ hostname }}
  become: yes
  notify:
    - restart nginx

- name: Ensure that the application site is enabled
  file: src=/etc/nginx/sites-available/{{ hostname }}
        dest=/etc/nginx/sites-enabled/{{ hostname }}
        state=link
  become: yes
  notify: restart nginx

- name: Ensure Nginx service is started
  service: name=nginx state=started enabled=yes
