# Clone the repo

- name: Set up git configuration
  apt: name=git state=latest
  become: yes

- name: Clone or pull the latest code
  git:
    repo: "{{ backend_repository_url }}"
    dest: "{{ backend_remote_dir }}"
    version: "{{ backend_repository_branch }}"