# Run migrations for database after creation of required config file

- name: Write database conf file
  template: src=db_config dest="{{ backend_remote_dir }}/{{ django_project_name }}/config.py"
  become: yes
  notify:
    - restart nginx
    - restart application

- name: Run Django database migrations
  django_manage:
    command: migrate
    app_path: "{{ backend_remote_dir }}"
    virtualenv: "{{ venv_dir }}"
  tags: django.migrate
  notify:
    - restart nginx
    - restart application