# Set up systemd for executing gunicorn_start script

- name: Set up supervisorctl config
  apt: name=supervisor state=latest
  become: yes

- name: Ensure the Supervisor service is running
  service: name=supervisor state=started enabled=yes
  become: yes

- name: Create the Supervisor config file
  template: src=supervisor_config
            dest=/etc/supervisor/conf.d/{{ app_name }}.conf
            backup=yes
  become: yes

- name: Re-read the Supervisor config files
  supervisorctl: name={{ app_name }} state=present
  become: yes
  notify:
  - restart nginx
  - restart application
