##
# Configure the server for the Django app
##
- include: 01_server.yml
- include: 02_git.yml
- include: 03_postgres.yml
- include: 04_dependencies.yml
- include: 05_migrations.yml
- include: 06_gunicorn.yml
- include: 06_01_frontend.yml
- include: 07_certbot.yml
- include: 08_nginx.yml
- include: 09_supervisorctl.yml
- include: 10_cron.yml